version: '3'

services:
  historybackend:
    build: ./
    restart: always
    ports:
      - '3001:3001'

  websocketbackend:
    build: ./websocketbackend
    restart: always
    environment:
      HISTORY_API_URI: http://historybackend:3001/api/history
    ports:
      - '3002:3002'
